services:
  mai_db:
    image: postgres:17
    container_name: mai_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: mai_user
      POSTGRES_PASSWORD: mai_password
      POSTGRES_DB: mai_db
    ports:
      - "5433:5432"
    volumes:
      - mai_pgdata:/var/lib/postgresql/data

volumes:
  mai_pgdata:
